spring:
  application:
    name: microservices-bootstrap
  profiles:
    active: uat

server:
  port: 9090
  error:
    include-stacktrace: never
  shutdown: graceful # Enable graceful shutdown - waits for in-flight requests to complete
  lifecycle:
      # How long Spring waits for in-flight requests to finish before forcing shutdown
      # Must be less than: terminationGracePeriodSeconds (45) - preStop (10) = 35s.
      # Both terminationGracePeriodSeconds and preStop are set in K8s YAML file.
      timeout-per-shutdown-phase: 30s


management:
  metrics:
    enable:
      reactor.netty: true   # Enable Reactor Netty metrics
  endpoints:
    web:
      exposure:
        include: health, info
    enabled-by-default: false
  endpoint:
    health:
      enabled: true    # enables /actuator/health
      show-details: never
      probes:
        enabled: true  # enables both /actuator/health/liveness and /actuator/health/readiness
    info:
      enabled: true
    metrics:
      enabled: true

